# Generated by Django 3.2.9 on 2021-11-29 03:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='title')),
                ('body', models.TextField(blank=True, null=True, verbose_name='body')),
                ('link', models.CharField(blank=True, help_text='用户点击消息跳转的链接地址', max_length=200, null=True, verbose_name='链接')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='发送时间')),
                ('handler', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='my_send', to='accounts.user')),
                ('users', models.ManyToManyField(to='accounts.User', verbose_name='用户')),
            ],
            options={
                'verbose_name': '发送记录',
                'verbose_name_plural': '发送记录',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='title')),
                ('body', models.TextField(blank=True, null=True, verbose_name='body')),
                ('link', models.CharField(blank=True, help_text='用户点击消息跳转的链接地址', max_length=200, null=True, verbose_name='链接')),
                ('is_read', models.BooleanField(default=False, verbose_name='is read')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.user', verbose_name='receiver user')),
            ],
            options={
                'verbose_name': 'inbox',
                'verbose_name_plural': 'inbox',
                'ordering': ['-created'],
            },
        ),
    ]
